#!/bin/sh
#
# sched_open
# purpose: builds schedule's open list
# usage: linked from include/menu.html
#

#echo "start In sched_open: $$ $1 $2 $3" | mutt -s "sched_open" ericl@borisch.com

#. ./fpsetenv.bat

# GET PARAMETER FROM QUERY STRING

SCHED=$1
DESC=$2
LANG=$3

export LANG

HTML_RESP_FILE=/appl/fpmerge/sched_open$$.tmp

>$HTML_RESP_FILE
chmod 640 $HTML_RESP_FILE
export HTML_RESP_FILE

/appl/fp/dreport scheduling -fp open -sr 1 -u -r "$$" -rw "$SCHED" -rx "$DESC" >> /dev/null

# $SCHED is type, $DESC is description

#echo Content-type: text/html
#echo

cat $HTML_RESP_FILE
rm -f $HTML_RESP_FILE

